### ISSUE TITLE
Include busybox for amd64 arch

### ISSUE THREAD

**Issue by darkskiez** [gokrazy/serial-busybox#1]
For using with qemu etc.

**Comment by anupcshan** [comment]
I had a similar need, but for armhf instead of amd64. I have a functioning busybox (for amd64/arm64/armhf) in https://github.com/anupcshan/gokrazy-busybox. @stapelberg Mind if I send some pull requests?

**Comment by stapelberg** [comment]
@anupcshan Please do!

**Comment by stapelberg** [comment]
Note that we don’t officially support armhf as per https://gokrazy.org/platforms/, but I don’t mind adding an armhf busybox build here anyway.

**Comment by anupcshan** [comment]
Yep, I understand armhf is not officially supported. I managed to get gokrazy running on an Odroid HC2 with some tweaks - its CPU is unfortunately armhf only.
